{!! $EMAIL_SALUTATION !!} {!! $EMAIL_CUSTOMERS_NAME !!},

{!! $EMAIL_TEXT_ORDER_NUMBER !!}
{!! $EMAIL_OSH_EMAIL_TEXT_INVOICE_URL !!} {!! $EMAIL_TEXT_INVOICE_URL !!}
{!! $EMAIL_TEXT_DATE_ORDERED !!}
@if($EMAIL_TEXT_STATUS_COMMENTS)
{!! $EMAIL_TEXT_COMMENTS_UPDATE !!} {!! strip_tags($EMAIL_TEXT_STATUS_COMMENTS) !!}
@endif

{!! $EMAIL_TEXT_STATUS_UPDATED !!}
@if($ORDER_STATUS)

{!! $EMAIL_TEXT_STATUS_LABEL !!} {!! $ORDER_STATUS !!}
@else

{!! $EMAIL_TEXT_STATUS_CHANGE_OLD !!} {{ $OLD_ORDER_STATUS }}. {!! $EMAIL_TEXT_STATUS_CHANGE_NEW !!}<strong> {{ $NEW_ORDER_STATUS }}.
@endif

{!! $EMAIL_TEXT_STATUS_PLEASE_REPLY !!}
{!! $EMAIL_STORE_NAME !!}
@if ($EMAIL_ORDER_UPDATE_MESSAGE)
{!! $EMAIL_ORDER_UPDATE_MESSAGE or '' !!}
@endif
@if ($EMAIL_PAYPAL_TRANSID)
PayPal Trans ID {!! $EMAIL_PAYPAL_TRANSID !!}
@endif